version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pratti

  spring-app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pratti
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    command: >
      bash -c "dockerize -wait tcp://mysql:3306 -timeout 60s &&
      java -jar app.jar"
